-- 프로시저를 통해 사원본호를 입력하면 사원이름/사원월급/사원직책 매개변수를 통해 전달. --

CREATE OR REPLACE PROCEDURE EMP_PROCEDURE_OUTMODE
(
    VEMPNO IN EMPLOYEES.EMPLOYEE_ID%TYPE,
    VNAME OUT EMPLOYEES.FIRST_NAME%TYPE,
    VSALARY OUT EMPLOYEES.SALARY%TYPE,
    VJOBID OUT EMPLOYEES.JOB_ID%TYPE
)
IS
    -- 지역 변수. --

BEGIN
    --SELECT FIRST_NAME, SALARY, JOB_ID FROM EMPLOYEES WHERE EMPLOYEE_ID=100;
    SELECT FIRST_NAME, SALARY, JOB_ID INTO VNAME, VSALARY, VJOBID FROM EMPLOYEES WHERE EMPLOYEE_ID=VEMPNO;

--EXCEPTION

END;
/

-- EXCE를 사용하면 값을 입력하는게 불가함.

DECLARE
    VEMP_ROWTYPE EMPLOYEES%ROWTYPE;

BEGIN
    -- 변수명은 달라도 되지만, 타입은 항상 같게 해야 함.
    EMP_PROCEDURE_OUTMODE(100,
    VEMP_ROWTYPE.FIRST_NAME,
    VEMP_ROWTYPE.SALARY,
    VEMP_ROWTYPE.JOB_ID
    );
    
    DBMS_OUTPUT.PUT_LINE('이름 : '||VEMP_ROWTYPE.FIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('봉급 : '||VEMP_ROWTYPE.SALARY);
    DBMS_OUTPUT.PUT_LINE('직책 : '||VEMP_ROWTYPE.JOB_ID);

END;
/

-- 프로시저를 워크시트 밖에서 불러 사용.
VARIABLE VNAME VARCHAR2(100)
VARIABLE VSALARY NUMBER
VARIABLE VJOBID VARCHAR2(10)

EXECUTE EMP_PROCEDURE_OUTMODE(200, :VNAME, :VSALARY, :VJOBID);

PRINT VNAME;
PRINT VSALARY;
PRINT VJOBID;