CREATE TABLE TEST241121
{


SELECT EMP_NAME, EMP_NO, DEPT_CODE, SALARY

FROM EMPLOYEE

WHERE DEPT_CODE='D9' OR DEPT_CODE='D6' AND SALARY > 3000000

AND EMAIL LIKE '____%' AND BONUS IS NULL;

CREATE TABLE TEST241121
AS
SELECT * FROM EMPLOYEES;

SELECT * FROM TEST241121;

SELECT DEPARTMENT_ID, SUM(SALARY) 합계, FLOOR(AVG(SALARY)) 평균, COUNT(*) 인원수
FROM TEST241121
WHERE SALARY > 10000
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID ASC;

SELECT ROWNUM, FIRST_NAME, SALARY FROM TEST241121
WHERE ROWNUM <= 3
ORDER BY SALARY DESC;

SELECT * FROM TEST241121;

INSERT INTO TEST241121 VALUES(999, 'testTest', 'testTest', 'testTest', '0000000000', 'test_TEST', '9.9.9', 50000, 9, 999, 99);




CREATE VIEW test241121_2
AS
SELECT employee_id, first_name, salary, E.department_id, department_name, location_id
FROM employees E INNER JOIN departments D ON E.department_id=D.department_id
ORDER BY department_id DESC;

CREATE TABLE TEST_DEPARTMENT(
DEPTCODE NUMBER PRIMARY KEY,
DEPTNAME NVARCHAR2(10) NOT NULL
);

CREATE TABLE TEST_EMPLOYEE(
EMPNO NUMBER PRIMARY KEY,
EMPNAME VARCHAR2(10) NOT NULL,
DEPTNO NUMBER REFERENCES TEST_DEPARTMENT(DEPTCODE)
);

SELECT EMPNO, EMPNAME, DEPTNO, DEPTNAME
FROM TEST_EMPLOYEE E
JOIN TEST_DEPARTMENT D ON E.DEPTNO=D.DEPTCODE;
