CREATE PROCEDURE PROCEDURE_NAME

IS
    VWORD VARCHAR2(1);
    VEMP EMPLOYEES%ROWTYPE;
    CURSOR C1(VWORD VARCHAR2)
    IS
    SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
    FROM EMPLOYEES
    WHERE FIRST_NAME LIKE '%'||VWORD||'%';

BEGIN
    VWORD := DBMS_RANDOM.STRING('U', 1);
    DBMS_OUTPUT.PUT_LINE('임의의 문자 : '||VWORD);
    OPEN C1(VWORD);
    DBMS_OUTPUT.PUT_LINE('직원번호 / 직원명 / 급여');
    DBMS_OUTPUT.PUT_LINE('=====================');
    LOOP
    FETCH C1 INTO VEMP.EMPLOYEE_ID, VEMP.FIRST_NAME, VEMP.SALARY;
    
    IF
    C1%ROWCOUNT=0
    THEN
    DBMS_OUTPUT.PUT_LINE('해당 직원이 존재하지 않습니다.');
    
    END IF;
    EXIT WHEN C1%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(VEMP.EMPLOYEE_ID||'/'||VEMP.FIRST_NAME||'/'||VEMP.SALARY);
    
    END LOOP;

END;

/

-- 생성된 저장 프로시저 실행 명령어. --
EXECUTE PROCEDURE_NAME;
EXEC PROCEDURE_NAME;

-- 저장 프로시저 생성 확인 명령어. --
SELECT * FROM USER_SOURCE;

-- 상세 오류메시지 출력 명령어. --
SHOW ERROR;

