CREATE SEQUENCE visit_seq  -- 시퀀스이름
   START WITH 1             -- 시작을 1로 설정
   INCREMENT BY 1          -- 증가 값을 1씩 증가
   NOMAXVALUE             -- 최대 값이 무한대
   NOCACHE
   NOCYCLE;

CREATE table VISIT
(
    NO         NUMBER(5,0) NOT NULL,
    WRITER     VARCHAR2(20) NOT NULL,
    MEMO     VARCHAR2(4000) NOT NULL,
    REGDATE   DATE NOT NULL
-- constraint VISIT_PK primary key (NO)
);

ALTER TABLE VISIT ADD CONSTRAINT VISIT_NO_PK PRIMARY KEY(NO);

INSERT INTO VISIT VALUES(VISIT_seq.NEXTVAL, 'ppp', 'test', SYSDATE);

select * from visit;

-- 회원가입 테이블(MEMBER) --
CREATE TABLE MEMBER
(
    NO NUMBER,  -- pk
    ID VARCHAR2(20),    --uk
    PWD VARCHAR2(20),
    ADDRESS VARCHAR2(100),
    REGDATE DATE NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_NO_PK PRIMARY KEY(NO);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_ID_UK UNIQUE(ID);

DROP TABLE MEMBER;
SELECT * FROM MEMBER;
SELECT * FROM MEMBER ORDER BY NO;

INSERT INTO MEMBER VALUES(MEMBER_seq.NEXTVAL, 'member01@daum.net', 'member01', '서울시 서초구 서초동', SYSDATE);
INSERT INTO MEMBER VALUES(MEMBER_seq.NEXTVAL, 'member02@daum.net', 'member02', '서울시 강남구 역삼동', SYSDATE);
INSERT INTO MEMBER VALUES(MEMBER_seq.NEXTVAL, 'member03@daum.net', 'member03', '서울시 강남구 강남동', SYSDATE);

CREATE SEQUENCE MEMBER_seq  -- 시퀀스이름
   START WITH 1             -- 시작을 1로 설정
   INCREMENT BY 1          -- 증가 값을 1씩 증가
   NOMAXVALUE             -- 최대 값이 무한대
   NOCACHE
   NOCYCLE;  

-- LOGIN -----------------------------------------------------------------------
CREATE table LOGIN
(
     ID VARCHAR2(12) NOT NULL,
     PASS VARCHAR2(12) NOT NULL
);
SELECT * FROM LOGIN;
ALTER TABLE LOGIN ADD CONSTRAINT LOGIN_ID_PK PRIMARY KEY(ID);

CREATE SEQUENCE LOGIN_seq  -- 시퀀스이름
   START WITH 1             -- 시작을 1로 설정
   INCREMENT BY 1          -- 증가 값을 1씩 증가
   NOMAXVALUE             -- 최대 값이 무한대
   NOCACHE
   NOCYCLE;
   
INSERT INTO LOGIN VALUES('member01', '123456');

SELECT * FROM LOGIN;





---------------
CREATE TABLE ACCOUNT
(
    NO NUMBER(5, 0)  NOT NULL,-- pk
    NAME VARCHAR2(20) NOT NULL,
    ID VARCHAR2(4000) NOT NULL,    --uk
    PWD VARCHAR2(4000) NOT NULL,
    REGDATE DATE NOT NULL
);

ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_NO_PK PRIMARY KEY(NO);
ALTER table ACCOUNT add constraint ACCOUNT_ID_UK UNIQUE(id);


INSERT INTO ACCOUNT VALUES((select NVL(max(no),0)+1 from ACCOUNT), 'AAA', 'AAA', 'AAA', SYSDATE);
SELECT * FROM ACCOUNT ORDER BY NO;

SELECT PWD FROM ACCOUNT WHERE ID = 'BBB';

SELECT * FROM ACCOUNT ORDER BY NO;

SELECT * FROM ACCOUNT WHERE ID = '태스트09' AND PWD = '123';


UPDATE ACCOUNT SET ID='BBB', PWD='BBB' WHERE ID='AAA';
COMMIT;