-- [CAFE DB]MENU (최상위) ----------------------------------------------------------------------------------------------------
CREATE TABLE MENU
(
    NO NUMBER,  -- pk
    DRINK VARCHAR2(20) NOT NULL, -- NOT NULL
    SNACK VARCHAR2(20),
    DESSERT VARCHAR2(20)
);

SELECT * FROM MENU ORDER BY NO;
SELECT NO, DRINK, NVL(SNACK, ' ') AS SNACK, NVL(DESSERT, ' ')AS DESSERT FROM MENU ORDER BY NO;

DROP TABLE MENU;
DESC MENU;
ALTER TABLE MENU DROP COLUMN IN_OR_OUT;

ALTER TABLE MENU ADD CONSTRAINT MENU_NO_PK PRIMARY KEY(NO);

CREATE SEQUENCE MENU_NO_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO MENU VALUES(MENU_NO_SEQ.nextval, '아메리카노', '초코쿠키', '초코케익');

-- [CAFE DB]EVENT GOODS (MENU테이블로부터 NO를 참조.) -------------------------------------------------------------------------------
CREATE TABLE EVENT
(
    NO NUMBER,  -- fk(MENU테이블로부터 NO참조.)
    AREA VARCHAR2(30),
    COUNT NUMBER(2) NOT NULL
);

ALTER TABLE EVENT ADD CONSTRAINT EVENT_NO_FK FOREIGN KEY(NO) REFERENCES MENU(NO) ON DELETE CASCADE;
ALTER TABLE EVENT DROP PRIMARY KEY;
ALTER TABLE EVENT DROP COLUMN AREA;
ALTER TABLE EVENT ADD AREA VARCHAR2(30);
DELETE FROM EVENT WHERE NO=1;

INSERT INTO EVENT(NO, AREA, COUNT) VALUES(1, '강남R점', 2);
INSERT INTO EVENT(NO, AREA, COUNT) VALUES(2, '강남R점', 1);

SELECT * FROM EVENT;

------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REVIEW
(
    M_NUM NUMBER,   -- fk(MENU테이블로부터 NO참조.)
    REVIEW VARCHAR2(100)
);

ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_M_NUM_FK FOREIGN KEY(M_NUM) REFERENCES MENU(NO) ON DELETE CASCADE;
INSERT INTO REVIEW(M_NUM, REVIEW) VALUES(5, '매장이 깔끔하고, 직원들이 친절함.');

SELECT * FROM REVIEW;

DELETE FROM REVIEW WHERE M_NUM=5;

SELECT M.NO, M.DRINK, M.SNACK, M.DESSERT, R.REVIEW FROM REVIEW R INNER JOIN MENU M ON R.M_NUM=M.NO WHERE M_NUM=R.M_NUM;
SELECT M.NO, M.DRINK, M.SNACK, M.DESSERT, R.REVIEW FROM REVIEW R INNER JOIN MENU M ON R.M_NUM=M.NO WHERE 2=M_NUM;
SELECT M.NO, M.DRINK, M.SNACK, M.DESSERT, R.REVIEW FROM REVIEW R INNER JOIN MENU M ON R.M_NUM=M.NO;
SELECT M_NUM, M.DRINK, M.SNACK, M.DESSERT, R.REVIEW FROM REVIEW R INNER JOIN MENU M ON R.M_NUM=M.NO;

SELECT M_NUM, M.DRINK, NVL(M.SNACK, ' ') AS SNACK, NVL(M.DESSERT, ' ') AS DESSERT, R.REVIEW FROM REVIEW R INNER JOIN MENU M ON R.M_NUM=M.NO;





























-- [CAFE DB]ORDER_CHECK (MENU테이블로부터 NO를 참조.) --
CREATE TABLE ORDER_CHECK
(/*primary key 없어도 되려나.......?*/
    M_NUM NUMBER   -- fk(MENU테이블로부터 NO참조.)
);

ALTER TABLE ORDER_CHECK ADD CONSTRAINT ORDER_CHECK_M_NUM_FK FOREIGN KEY(M_NUM) REFERENCES MENU(NO) ON DELETE CASCADE;
-- ALTER TABLE ORDER_CHECK ADD CONSTRAINT ORDER_CHECK_E_AREA_FK FOREIGN KEY(E_AREA) REFERENCES EVENT(AREA) ON DELETE CASCADE;

SELECT * FROM ORDER_CHECK;

INSERT INTO ORDER_CHECK(M_NUM) VALUES(5);
--SELECT M.NO, M.DRINK, M.SNACK, M.DESSERT FROM ORDER_CHECK OC INNER JOIN MENU M ON OC.M_NUM=M.NO WHERE M_NUM=R;


--SELECT * FROM EVENT E INNER JOIN MENU M ON E.NO=M.NO WHERE M.NO=2;

--SELECT * FROM ORDER_CHECK OC INNER JOIN MENU M ON OC.M_NUM=M.NO WHERE M.NO=1;

DROP TABLE ORDER_CHECK;
SELECT * FROM ORDER_CHECK;