CREATE TABLE MEMBER
(
    ID VARCHAR2(20) NOT NULL,   -- PK.
    PWD VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    PHONE1 VARCHAR2(4) NOT NULL,
    PHONE2 VARCHAR2(4) NOT NULL,
    PHONE3 VARCHAR2(4) NOT NULL,
    EMAIL VARCHAR2(40) NOT NULL,
    ZIPCODE VARCHAR2(10) NOT NULL,
    ADDRESS1 VARCHAR2(100) NOT NULL,
    ADDRESS2 VARCHAR2(100) NOT NULL  
);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_ID_PK PRIMARY KEY(ID);

INSERT INTO MEMBER VALUES(?,?,?,?,?,?,?,?,?,?);
SELECT * FROM MEMBER;

CREATE TABLE ZIPCODE
(
    SEQ NUMBER(10) NOT NULL,
    ZIPCODE VARCHAR2(50),
    SIDO VARCHAR2(50),
    GUGUN VARCHAR2(50),
    DONG VARCHAR2(50),
    BUNJI VARCHAR2(100)
);

ALTER TABLE ZIPCODE add constraint ZIPCODE_SEQ_PK primary key(SEQ);

SELECT * FROM ZIPCODE;
SELECT * FROM MEMBER;
UPDATE MEMBER SET PWD='1234', phone1='02', phone2='1234', phone3='1234', email='test04@naver.com', zipcode='2', address1='2', address2='2' WHERE id='test04';
COMMIT;

CREATE TABLE BOARD
(
    NUM NUMBER(7,0) NOT NULL,
    WRITER VARCHAR2(12) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    SUBJECT VARCHAR2(50) NOT NULL,
    PASS VARCHAR2(10) NOT NULL,
    READCOUNT NUMBER(5,0) DEFAULT 0, 
    "REF" NUMBER(5,0) DEFAULT 0, 
    STEP NUMBER(3,0) DEFAULT 0, 
    "DEPTH" NUMBER(3,0) DEFAULT 0, 
    REGDATE TIMESTAMP (6) DEFAULT SYSDATE, 
    "CONTENT" VARCHAR2(4000) NOT NULL,
    IP VARCHAR2(20) NOT NULL ENABLE
);

ALTER TABLE BOARD ADD CONSTRAINT BOARD_NUM_PK PRIMARY KEY(NUM);
 
CREATE SEQUENCE BOARD_SEQ-- 시퀀스이름
START WITH 1 -- 시작번호 1.
INCREMENT BY 1 -- 번호 증가값 1.
NOMAXVALUE -- 최대값이 무한대.
NOCACHE
NOCYCLE;

SELECT * FROM BOARD;

DELETE FROM BOARD WHERE NUM =2 AND PASS =123;
COMMIT;

-- 로그인 한 회원에게만 글쓰기 권한. --
CREATE TABLE QANDA
(
    NUM NUMBER(7,0) NOT NULL,
    WRITER VARCHAR2(12) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    SUBJECT VARCHAR2(50) NOT NULL,
    PASS VARCHAR2(10) NOT NULL,
    READCOUNT NUMBER(5,0) DEFAULT 0, 
    "REF" NUMBER(5,0) DEFAULT 0, 
    STEP NUMBER(3,0) DEFAULT 0, 
    "DEPTH" NUMBER(3,0) DEFAULT 0, 
    REGDATE TIMESTAMP (6) DEFAULT SYSDATE, 
    "CONTENT" VARCHAR2(4000) NOT NULL,
    IP VARCHAR2(20) NOT NULL ENABLE
);

-- 관리자 계정 로그인. --
CREATE TABLE ADMIN
(
    ID VARCHAR2(20) NOT NULL,   -- PK.
    PWD VARCHAR2(20) NOT NULL
);

ALTER TABLE ADMIN ADD CONSTRAINT ADMIN_ID_PK PRIMARY KEY(ID);

INSERT INTO ADMIN VALUES ('admin', '1234');
SELECT * FROM ADMIN;
COMMIT;

CREATE TABLE PRODUCTS
(
    NO NUMBER(3),
    NAME VARCHAR2(100),
    PRICE VARCHAR2(50),
    USE_PERIOD NUMBER(3)
);

ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCTS_NAME_PK PRIMARY KEY(NAME);

CREATE SEQUENCE PRODUCTS_SEQ  -- 시퀀스이름
START WITH 1             -- 시작을 1로 설정
INCREMENT BY 1          -- 증가 값을 1씩 증가
NOMAXVALUE             -- 최대 값이 무한대
NOCACHE
NOCYCLE;

INSERT INTO PRODUCTS VALUES(PRODUCTS_SEQ.NEXTVAL, 'TEST01', '12,000', '3');
INSERT INTO PRODUCTS VALUES(PRODUCTS_SEQ.NEXTVAL, 'TEST02', '12,000', '3');
UPDATE PRODUCTS SET PRICE='14,000', USE_PERIOD='4' WHERE NAME='TEST01';
DELETE FROM PRODUCTS WHERE NO=42;
ALTER TABLE PRODUCTS MODIFY PRICE NOT NULL;
ALTER TABLE PRODUCTS MODIFY USE_PERIOD NOT NULL;
SELECT * FROM PRODUCTS WHERE NO=31;

COMMIT;

SELECT * FROM PRODUCTS;

COMMIT;

CREATE TABLE CART
(
    NO NUMBER(3),
    NAME VARCHAR2(100), -- pk & fk.
    PRICE VARCHAR2(50),
    USE_PERIOD NUMBER(3),   -- fk.
    TOTAL_PRICE NUMBER(6)
);

ALTER TABLE CART ADD CONSTRAINT CART_NAME_PK PRIMARY KEY(NAME);
ALTER TABLE CART ADD CONSTRAINT CART_NAME_FK FOREIGN KEY(NAME) REFERENCES PRODUCTS(NAME);

CREATE SEQUENCE CART_SEQ  -- 시퀀스이름
START WITH 1             -- 시작을 1로 설정
INCREMENT BY 1          -- 증가 값을 1씩 증가
NOMAXVALUE             -- 최대 값이 무한대
NOCACHE
NOCYCLE;

/* 관리자 상품 등록 테이블. *****************************/
CREATE TABLE INSERT_PRODUCTS
(
    product_id	NUMBER(5),	-- 상품 고유 ID (Primary Key)
    name	VARCHAR(255),	-- 상품명
    description	VARCHAR(255),	-- 상품 설명
    price	DECIMAL(10,2),	-- 가격
    -- stock_quantity	NUMBER(5),	-- 재고 수량
    -- category	VARCHAR(100),	-- 상품 카테고리
    image_url	VARCHAR(255),	-- 상품 이미지 URL
    created_at	TIMESTAMP,	-- 상품 등록일
    updated_at	TIMESTAMP	-- 상품 수정일
);

ALTER TABLE INSERT_PRODUCTS ADD CONSTRAINT INSERT_PRODUCTS_PRODUCT_ID_PK PRIMARY KEY(product_id);

INSERT INTO INSERT_PRODUCTS (product_id, name, description, price, created_at, updated_at)
VALUES (INSERT_PRODUCTS_SEQ.NEXTVAL, 'test02', '설명02', 15000, SYSDATE, SYSDATE);

INSERT INTO INSERT_PRODUCTS (product_id, name, description, price, image_url, created_at, updated_at)
VALUES (INSERT_PRODUCTS_SEQ.NEXTVAL, 'TEST_LISTENING_01', '이용권 등록 테스트01', 15000, 'test_url_01', SYSDATE, SYSDATE);

CREATE SEQUENCE INSERT_PRODUCTS_SEQ  -- 시퀀스이름
START WITH 1             -- 시작을 1로 설정
INCREMENT BY 1          -- 증가 값을 1씩 증가
NOMAXVALUE             -- 최대 값이 무한대
NOCACHE
NOCYCLE;



SELECT * FROM INSERT_PRODUCTS;

DROP SEQUENCE INSERT_PRODUCTS_SEQ;
DROP TABLE INSERT_PRODUCTS;

COMMIT;